name: sandbox_digilocker_sdk
description: "Embed Sandbox's Digilocker SDK in your flutter app."
version: 1.0.0
homepage: "https://sandbox.co.in/"

environment:
  sdk: ^3.4.0
  flutter: ^3.19.0

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0